CREATE TABLE "FLIGHT"(
                          "ID" SERIAL NOT NULL,
                          "DESTINATION" VARCHAR(255) NOT NULL,
                          "ORIGIN" VARCHAR(255) NOT NULL,
                          "ECON_PRICE" FLOAT(53) NOT NULL,
                          "BUSI_PRICE" FLOAT(53) NOT NULL,
                          "DATE" DATE NOT NULL,
                          "SCALE" BOOLEAN NOT NULL,
                          "AIRLINE" VARCHAR(255) NOT NULL,
                          "ECON_AVAIB_SEATS" INTEGER NOT NULL,
                          "BUSI_AVAIB_SEATS" INTEGER NOT NULL
);

ALTER TABLE
    "FLIGHT" ADD PRIMARY KEY("ID");

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('New York', 'London', '2024-09-01', 500, 1000, FALSE, 'American AIRLINEs', 100, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('New York', 'Paris', '2024-09-03', 450, 900, TRUE, 'Delta AIRLINEs', 120, 18);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Los Angeles', 'Tokyo', '2024-09-05', 800, 1600, TRUE, 'Japan AIRLINEs', 150, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Berlin', 'Rome', '2024-09-10', 300, 600, FALSE, 'Lufthansa', 80, 10);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Paris', 'New York', '2024-09-15', 650, 1300, FALSE, 'Air France', 110, 25);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('London', 'Sydney', '2024-09-20', 1200, 2400, TRUE, 'Qantas', 90, 15);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Rome', 'Berlin', '2024-09-22', 320, 640, FALSE, 'Alitalia', 85, 12);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Tokyo', 'Los Angeles', '2024-09-25', 780, 1560, TRUE, 'ANA', 130, 25);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Sydney', 'London', '2024-09-30', 1150, 2300, TRUE, 'British Airways', 100, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('New York', 'Los Angeles', '2024-10-01', 400, 800, FALSE, 'United AIRLINEs', 150, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Paris', 'Berlin', '2024-10-05', 350, 700, FALSE, 'Air France', 75, 15);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('London', 'Rome', '2024-10-07', 500, 1000, FALSE, 'British Airways', 100, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Chicago', 'Tokyo', '2024-09-12', 900, 1800, TRUE, 'ANA', 140, 28);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Madrid', 'Lisbon', '2024-09-13', 250, 500, FALSE, 'Iberia', 70, 10);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Beijing', 'Shanghai', '2024-09-14', 200, 400, FALSE, 'China Eastern', 160, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Sydney', 'Auckland', '2024-09-18', 450, 900, FALSE, 'Qantas', 95, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Dubai', 'London', '2024-09-21', 1100, 2200, TRUE, 'Emirates', 85, 18);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Frankfurt', 'New York', '2024-09-24', 600, 1200, FALSE, 'Lufthansa', 125, 22);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Miami', 'Cancun', '2024-09-28', 350, 700, FALSE, 'American Airlines', 100, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Bangkok', 'Singapore', '2024-10-02', 300, 600, FALSE, 'Thai Airways', 110, 25);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Amsterdam', 'London', '2024-10-04', 400, 800, FALSE, 'KLM', 120, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Seoul', 'Tokyo', '2024-10-08', 500, 1000, FALSE, 'Korean Air', 140, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Toronto', 'Vancouver', '2024-10-10', 450, 900, FALSE, 'Air Canada', 130, 25);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Mexico City', 'Miami', '2024-10-12', 380, 760, FALSE, 'Aeromexico', 120, 18);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Moscow', 'Berlin', '2024-10-14', 320, 640, FALSE, 'Aeroflot', 95, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Cape Town', 'Johannesburg', '2024-10-15', 200, 400, FALSE, 'South African Airways', 75, 15);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Buenos Aires', 'Santiago', '2024-10-17', 300, 600, FALSE, 'LATAM', 80, 12);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Melbourne', 'Perth', '2024-10-19', 350, 700, FALSE, 'Qantas', 110, 25);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Dubai', 'Mumbai', '2024-10-20', 400, 800, FALSE, 'Emirates', 150, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('San Francisco', 'Vancouver', '2024-10-22', 380, 760, FALSE, 'United Airlines', 120, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Rio de Janeiro', 'São Paulo', '2024-10-23', 180, 360, FALSE, 'Gol Airlines', 85, 10);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('London', 'New Delhi', '2024-10-25', 850, 1700, TRUE, 'British Airways', 90, 18);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Toronto', 'Chicago', '2024-10-27', 280, 560, FALSE, 'Air Canada', 100, 15);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Mexico City', 'Madrid', '2024-10-30', 700, 1400, TRUE, 'Iberia', 110, 20);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Hong Kong', 'Bangkok', '2024-11-02', 350, 700, FALSE, 'Cathay Pacific', 140, 30);

INSERT INTO "FLIGHT" ("ORIGIN", "DESTINATION", "DATE", "ECON_PRICE", "BUSI_PRICE", "SCALE", "AIRLINE", "ECON_AVAIB_SEATS", "BUSI_AVAIB_SEATS")
VALUES ('Paris', 'Tokyo', '2024-11-04', 950, 1900, TRUE, 'Air France', 130, 25);
